version: "3.3"
services:
  # Hopital, soigne (redémarre) les containers unhealthy
  autoheal:
    image: willfarrell/autoheal
    environment:
      - "AUTOHEAL_CONTAINER_LABEL=all"
    networks: # prevent docker from creating a default driver for this container
      local:
        ipv4_address: 192.168.99.99
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  # SIMULATION POSTES
  simul-commercial:
    image: d34d/projet-admin:employes-commercial
    build: ./employes/commercial
    dns: 192.168.0.2
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
    networks:
      local:
        ipv4_address: 192.168.2.129
    volumes:
      - ./certs/ca.crt:/usr/local/share/ca-certificates/ca.crt
    stdin_open: true
    tty: true

  simul-comptable:
    image: d34d/projet-admin:employes-comptable
    build: ./employes/comptable
    dns: 192.168.0.2
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
    networks:
      local:
        ipv4_address: 192.168.2.65
    volumes:
      - ./certs/ca.crt:/usr/local/share/ca-certificates/ca.crt
    stdin_open: true
    tty: true

  simul-direction:
    image: d34d/projet-admin:employes-direction
    build: ./employes/direction
    dns: 192.168.0.2
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
    networks:
      local:
        ipv4_address: 192.168.2.1
    volumes:
      - ./certs/ca.crt:/usr/local/share/ca-certificates/ca.crt
    stdin_open: true
    tty: true

  simul-ouvrier:
    image: d34d/projet-admin:employes-ouvrier
    build: ./employes/ouvrier
    dns: 192.168.0.2
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
    networks:
      local:
        ipv4_address: 192.168.2.97
    volumes:
      - ./certs/ca.crt:/usr/local/share/ca-certificates/ca.crt
    stdin_open: true
    tty: true

  simul-secretaire:
    image: d34d/projet-admin:employes-secretaire
    build: ./employes/secretaire
    dns: 192.168.0.2
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
    networks:
      local:
        ipv4_address: 192.168.2.33
    volumes:
      - ./certs/ca.crt:/usr/local/share/ca-certificates/ca.crt
    stdin_open: true
    tty: true

  # WEB
  web-reverseproxy:
    image: d34d/projet-admin:web-reverseproxy
    build: ./web/reverseproxy
    networks:
      local:
        ipv4_address: 192.168.0.5
    volumes:
      - "web-caddy-data:/data"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"

  web-server:
    image: d34d/projet-admin:web-server
    build: ./web/webserver
    networks:
      local:
        aliases:
          - "web-b2b"
          - "web-vitrine"
          - "web-interne"
        ipv4_address: 192.168.0.3
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
    volumes:
      - "web-server-crt:/etc/apache2/certificate"
    deploy:
      placement:
        constraints: [node.role == manager]

  web-db:
    image: d34d/projet-admin:web-db
    build: ./web/db
    networks:
      local:
        ipv4_address: 192.168.1.2
    volumes:
      - "web-db-data:/var/lib/mysql"
      - "web-db-crt:/etc/mysql/ssl"
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
    deploy:
      placement:
        constraints: [node.role == manager] # Pour que la db se lance tjrs au même endroit, avec le même volume

  # VPN
  vpn-server:
    image: d34d/projet-admin:vpn-server
    build: ./vpn
    networks:
      local:
        ipv4_address: 192.168.0.4
    ports:
      - "1194:1194/udp"
    volumes:
      - "vpn-crt:/etc/openvpn/certs"
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
      - "IPV6_64=${IPV6_64}"
    cap_add:
      - NET_ADMIN
    deploy:
      placement:
        constraints: [node.role == manager]

  # DNS
  dns:
    image: d34d/projet-admin:dns
    build: ./dns
    networks:
      local:
        ipv4_address: 192.168.0.2
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - "DOMAIN_NAME=${DOMAIN_NAME}"
      - "PUBLIC_IP=${PUBLIC_IP}"

networks:
  local:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16

volumes:
  web-db-data:
  web-db-crt:
  web-caddy-data:
  web-server-crt:
  vpn-crt:
